name: test-deploy

on:
  push:


jobs:
  branch_name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'cool cool'

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
          repository: Loki-Afro/test-bingo
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'